import { addDays, addWeeks, addMonths, startOfDay, parseISO } from 'date-fns'
import { repositories } from '../infrastructure/nocodebackend/repositories'
import { requireAuthenticatedUser } from '../infrastructure/nocodebackend/errors'
import { getDatabaseUserId } from './authStorage'
import { houseworkTaskFormSchema } from '../domains/schemas'
import { validateFormSubmission } from '../domains/validation'
const userId = () => requireAuthenticatedUser(getDatabaseUserId())
const calculateNextDueDate = (lastCompleted, frequency) => { const date = lastCompleted ? parseISO(lastCompleted) : new Date(); const amount = { daily: [addDays, 1], every_2_days: [addDays, 2], twice_weekly: [addDays, 3], weekly: [addWeeks, 1], biweekly: [addWeeks, 2], monthly: [addMonths, 1], quarterly: [addMonths, 3], seasonal: [addMonths, 6] }[frequency] ?? [addWeeks, 1]; return amount[0](date, amount[1]).toISOString() }
const dueToday = (task) => startOfDay(parseISO(task.next_due_date)).getTime() <= startOfDay(new Date()).getTime()

export const houseworkService = {
  async getHouseworkTasks(filters = {}) { let tasks = await repositories.houseworkTasks.list({ user_id: userId() }); if (filters.room) tasks = tasks.filter((task) => task.room === filters.room); if (filters.frequency) tasks = tasks.filter((task) => task.frequency === filters.frequency); if (filters.dueToday) tasks = tasks.filter(dueToday); return tasks.sort((a, b) => new Date(a.next_due_date) - new Date(b.next_due_date)) },
  async createHouseworkTask(input) { const data = validateFormSubmission(houseworkTaskFormSchema, input, 'Invalid housework task submission.'); return repositories.houseworkTasks.create({ user_id: userId(), task_type: 'housework', title: data.title, description: data.description || '', room: data.room, frequency: data.frequency, estimated_duration: data.estimated_duration || 30, prep_time: data.prep_time || 0, cleanup_time: data.cleanup_time || 0, checklist: data.checklist || [], required_items: data.required_items || [], is_essential: data.is_essential || false, is_active: true, mode: 'home', next_due_date: data.next_due_date || new Date().toISOString(), last_completed: null, completion_count: 0 }) },
  async completeHouseworkTask(taskId, completedChecklist = []) { const id = userId(); const task = await repositories.houseworkTasks.get(taskId, { user_id: id }); const completed_at = new Date().toISOString(); await repositories.houseworkCompletions.create({ user_id: id, task_id: taskId, completed_at, checklist_completed: completedChecklist, duration_actual: null }); return repositories.houseworkTasks.update(taskId, { last_completed: completed_at, completion_count: (task.completion_count || 0) + 1, next_due_date: calculateNextDueDate(completed_at, task.frequency), updated_at: completed_at }, { user_id: id }) },
  async snoozeTask(taskId) { const id = userId(); const task = await repositories.houseworkTasks.get(taskId, { user_id: id }); return repositories.houseworkTasks.update(taskId, { next_due_date: addDays(parseISO(task.next_due_date), 1).toISOString(), updated_at: new Date().toISOString() }, { user_id: id }) },
  async updateTaskStatus(taskId, is_active) { return repositories.houseworkTasks.update(taskId, { is_active, updated_at: new Date().toISOString() }, { user_id: userId() }) },
  async getCompletionHistory(taskId, limit = 30) { return (await repositories.houseworkCompletions.list({ user_id: userId(), task_id: taskId })).sort((a, b) => new Date(b.completed_at) - new Date(a.completed_at)).slice(0, limit) },
  async getHouseworkStats(days = 30) { const id = userId(); const [tasks, completions] = await Promise.all([repositories.houseworkTasks.list({ user_id: id }), repositories.houseworkCompletions.list({ user_id: id })]); const recent = completions.filter((item) => new Date(item.completed_at) >= new Date(Date.now() - days * 86400000)); return { total_tasks: tasks.length, active_tasks: tasks.filter((task) => task.is_active).length, total_completions: recent.length, completion_rate: tasks.length ? ((recent.length / (tasks.length * (days / 7))) * 100).toFixed(1) : 0, most_completed: this.getMostCompletedTask(tasks, recent), upcoming_today: tasks.filter((task) => task.is_active && dueToday(task)).length } },
  getMostCompletedTask(tasks, completions) { const counts = completions.reduce((all, item) => ({ ...all, [item.task_id]: (all[item.task_id] || 0) + 1 }), {}); const id = Object.keys(counts).sort((a, b) => counts[b] - counts[a])[0]; const task = tasks.find((value) => value.id === id); return task ? { title: task.title, count: counts[id] } : null },
  async balanceWeeklyTasks() { const tasks = (await this.getHouseworkTasks()).filter((task) => task.is_active); return Promise.all(tasks.map((task) => repositories.houseworkTasks.update(task.id, { next_due_date: task.next_due_date }, { user_id: userId() }))) },
  calculateNextDueDate
}
