import { repositories } from '../infrastructure/nocodebackend/repositories'
import { requireAuthenticatedUser } from '../infrastructure/nocodebackend/errors'
import { getDatabaseUserId } from './authStorage'
const userId = () => requireAuthenticatedUser(getDatabaseUserId())

export const routineProgressService = {
  async startRoutine(routineId, routine) { return repositories.routineSessions.create({ user_id: userId(), routine_id: routineId, routine_name: routine.name, started_at: new Date().toISOString(), current_step_index: 0, completed_steps: [], status: 'in_progress', total_steps: routine.routine_steps?.length || 0 }) },
  async getActiveSession(routineId) { const sessions = await repositories.routineSessions.list({ user_id: userId(), routine_id: routineId, status: 'in_progress' }); return sessions[0] ?? null },
  async completeStep(sessionId, stepIndex, stepId) { return this.updateSessionStep(sessionId, stepIndex, stepId, false) },
  async skipStep(sessionId, stepIndex, stepId) { return this.updateSessionStep(sessionId, stepIndex, stepId, true) },
  async updateSessionStep(sessionId, stepIndex, stepId, skipped) { const id = userId(); const session = await repositories.routineSessions.get(sessionId, { user_id: id }); const completed_steps = [...(session.completed_steps || []), { step_index: stepIndex, step_id: stepId, ...(skipped ? { skipped: true } : {}), completed_at: new Date().toISOString() }]; return repositories.routineSessions.update(sessionId, { completed_steps, current_step_index: stepIndex + 1, updated_at: new Date().toISOString() }, { user_id: id }) },
  async completeRoutine(sessionId) { return repositories.routineSessions.update(sessionId, { status: 'completed', completed_at: new Date().toISOString() }, { user_id: userId() }) },
  async cancelRoutine(sessionId) { return repositories.routineSessions.update(sessionId, { status: 'cancelled', cancelled_at: new Date().toISOString() }, { user_id: userId() }) },
  async getRoutineHistory(routineId, limit = 30) { return (await repositories.routineSessions.list({ user_id: userId(), routine_id: routineId, status: 'completed' })).sort((a, b) => new Date(b.completed_at) - new Date(a.completed_at)).slice(0, limit) },
  async getRoutineStats(routineId, days = 30) { const cutoff = Date.now() - days * 86400000; const sessions = (await this.getRoutineHistory(routineId)).filter((session) => new Date(session.completed_at).getTime() >= cutoff); const completed = sessions.reduce((sum, session) => sum + session.completed_steps.filter((value) => !value.skipped).length, 0); const skipped = sessions.reduce((sum, session) => sum + session.completed_steps.filter((value) => value.skipped).length, 0); return { total_completions: sessions.length, completion_rate: completed + skipped ? ((completed / (completed + skipped)) * 100).toFixed(1) : 0, average_completion_time: this.calculateAverageTime(sessions), current_streak: this.calculateStreak(sessions), last_completed: sessions[0]?.completed_at ?? null } },
  calculateAverageTime(sessions) { return sessions.length ? Math.round(sessions.reduce((sum, session) => sum + (new Date(session.completed_at) - new Date(session.started_at)) / 60000, 0) / sessions.length) : 0 },
  calculateStreak(sessions) { let streak = 0; let current = new Date(); current.setHours(0, 0, 0, 0); for (const session of [...sessions].sort((a, b) => new Date(b.completed_at) - new Date(a.completed_at))) { const date = new Date(session.completed_at); date.setHours(0, 0, 0, 0); if (Math.floor((current - date) / 86400000) !== 0) break; streak++; current.setDate(current.getDate() - 1) } return streak }
}
